name       : budgie-shutdown-timer
version    : 1.0
release    : 1
source     :
    - https://github.com/gkr09/budgie-shutdown-timer/archive/v1.0.tar.gz : cae471827d020bc1e361054741b8942f3ac1b9b7166a64242e1a5751fec7b14e
license    : GPL-3.0-or-later
component  : desktop.budgie
summary    : Schedule Shutdown/Restart etc. from your Budgie Desktop
description: |
   Automatically Shutdown/Reboot/Hibernate/Suspend after a set time.
builddeps  :
    - pkgconfig(budgie-1.0)
rundeps  :
    - budgie-desktop
install    : |
    %make_install
