name       : budgie-shutdown-timer
version    : 1.0
release    : 3
source     :
    - git|https://github.com/gkr09/budgie-shutdown-timer : d0cabf8ec85584ba305b6dc6eadc9ffecd739006
homepage   : https://github.com/gkr09/budgie-shutdown-timer
license    : GPL-3.0-or-later
component  : desktop.budgie
summary    : Schedule Shutdown/Restart etc. from your Budgie Desktop
description: |
    Automatically Shutdown/Reboot/Hibernate/Suspend after a set time.
builddeps  :
    - pkgconfig(budgie-1.0)
rundeps    :
    - budgie-desktop
install    : |
    %make_install
